# These types of DB containers use the publicly available Docker image
postgresql.container.image=postgres

# These types of DB containers must use a custom Operaton Docker image
# as they require a non-default Transaction Isolation level setup
mariadb.container.image=mariadb
mysql.container.image=mysql
mssql.container.image=mcr.microsoft.com/mssql/server
